### ISSUE TITLE
CWMarket causes crashes

### ISSUE THREAD

**Issue by Wolf1030** [fiote/treeofsavior-addons#12]
Sometimes it doesnt, but I've gotten 4 crashes in the last 10 mins. Basically when I go to the retrieve tab that's when it'll crash. I got a log from the client's log.

> SetEnable at [C](-1)
> 
> callback at ../addons/cwmarket/cwmarket.lua(64)
> 
> (null) at ../addons/cwapi/cwapi.lua(109)

**Comment by fiote** [comment]
I updated the release just after it went live, please download it again.
Or you can just get the cwmarket.lua file (https://github.com/fiote/treeofsavior-addons/blob/master/cwmarket/cwmarket.lua).

The problem happens when the addon tries to reach the buttons before the are created.
