### ISSUE TITLE
Not a real issue, but a question

### ISSUE THREAD

**Issue by Wolf1030** [fiote/treeofsavior-addons#13]
Yea I wish github had some sort of PM or general comment section for the authors. Anyways, I got a question for you in general.  Was wondering if the idea of an addon that auto skips the quest/ncp "dialog"  that we have to just skip through to get the to accepting/decline portion? Would be a nice "Quality of Life" addon or would that be more along the lines of being invasive by IMC's standards.

**Comment by fiote** [comment]
I tried to mess with NPC dialogs (with another goal in mind) but couldn't do much. I'll try that when I have time. Thanks for the sugestion :)
