### ISSUE TITLE
unsaved options and xpjobmin

### ISSUE THREAD

**Issue by Diolik** [fiote/treeofsavior-addons#14]
Hi.

farmed not loading options from json after restart game. loading only min options (silvermin, xpmin, xpjobmin).

and xpjobmin when i did 1% and defeated on boss in missions... i recieve 2% job, but no system message... after second boss, when i recive 3-3.5% job, i recieve system message 
xpjob 1,5% (2 mobs) in time..

Sorry for my terrible english.

**Comment by Diolik** [comment]
and didn't show pet exp if pet is Velheider. Hoglan is ok.

**Comment by fiote** [comment]
The saving part it's fixed on the newest release. About the pet exp on other pets... well... I know what may be wrong but I can't test it since I do own a second pet. I'll close this for now. Really sorry!
