### ISSUE TITLE
cwfarmed breaks anvil upgrading and (I think) re-rolling dungeon boxes

### ISSUE THREAD

**Issue by lukebitts** [fiote/treeofsavior-addons#15]
I was trying to upgrade an item and right-clicking the anvil wouldnt filter out the non upgradeable items, clicking the item to upgrade (after clicking the anvil) also wouldnt work. A while ago I realized I coudnt re-roll the dungeon boxes, so I decided to see if both problems were addon related. I disabled every addon and re-enabled them one by one, when I enabled cwfarmed I coudnt upgrade anymore. I don't have a dungeon box to open and test though, that's why I can't confirm.

JSON.lua version in the cwapi folder is 20141223.14

**Comment by holysnipz** [comment]
using which [release](https://github.com/fiote/treeofsavior-addons/releases)?

**Comment by lukebitts** [comment]
I downloaded `tos-lua-addons-fiote-20160510-01.zip` which is 2.0.0

**Comment by fiote** [comment]
Hi @lukebitts! Please download 2.1.0 since it contains a fix on cwfarmed ;)

**Comment by lukebitts** [comment]
I replaced with 2.1.0 and now both upgrading and rerolling is working. Thanks!
