### ISSUE TITLE
I can't make it work with Excrulon addon

### ISSUE THREAD

**Issue by Arr0gance** [fiote/treeofsavior-addons#19]
I've been using Excrulon + Better Quest addons so far but seems like I can't make it work with this addon, I don't know why I hope you can help me please. I've trying with the "addonloader.lua" from your folder but doesn't work in game so I need back to the addonloader.lua from the Excrulon.

**Comment by NannoNerd** [comment]
Me too! When i change the map the /cw /farmed and /shakeness stop to work... =/

**Comment by fiote** [comment]
@Arr0gance I advice you to get the new IPF addons from Excrulon. That probably will fix any conflict.
@NannoNerd So it starts fine and then stop working? Are you sure you're typing the commands on the normal chat? Because it doesnt work on party, guild, shout etc.

**Comment by fiote** [comment]
I'm closing this because i'm not fixing that now. All those problems will probably be solved when I move to IPF format, so it's better to talk about it only when that happens (if the problems persist).
