### ISSUE TITLE
Chat bug

### ISSUE THREAD

**Issue by vincentraulic** [fiote/treeofsavior-addons#2]
Hi Fiote,
I have that chat bug sometimes when i use your add on
![bug chat](https://cloud.githubusercontent.com/assets/2725840/14768103/43b35656-0a38-11e6-9ae3-3d3a1ca1e30e.png)

**Comment by fiote** [comment]
Hi Vincent, thanks for the report. Do you use any other addon too?

**Comment by vincentraulic** [comment]
Yes i'm using all this one : 
![aaaaaae](https://cloud.githubusercontent.com/assets/2725840/14769467/16bd1314-0a59-11e6-9836-a47acaec268e.png)

**Comment by Wolf1030** [comment]
same thing for me as well, same mods as Vince here.

**Comment by TehSeph** [comment]
That's caused by LKChat, not these addons.

**Comment by fiote** [comment]
Yeah, I knew it was a problem with LKChat but I though it could be some incompatibility between my addons and it. But I saw people on the forum that do not use my addon complaining about it, so I think it's safe to assume the problem is not on me.

**Comment by dothuraka** [comment]
Hey, just a question for @Wolf1030 and @vincentraulic, how to code boss intro skipper? I cannot find one, so I wish to create one for me.
