### ISSUE TITLE
farmed silver off doesn't work

### ISSUE THREAD

**Issue by YamashitaRen** [fiote/treeofsavior-addons#22]
Used /farmed silver off.
Pop-up appeared.
/farmed tells me that famed silver is indeed on "off".
Though I still have the farmed silver messages...

**Comment by fiote** [comment]
Hi @YamashitaRen! Indeed, the flag was not being actually checked. It's already fixed on the source files, but I still need to get a release for it. I'll let you know here when it's ready =]

**Comment by fiote** [comment]
Fixed on 3.0.0 https://github.com/fiote/treeofsavior-addons/releases/latest
