### ISSUE TITLE
Saved settings

### ISSUE THREAD

**Issue by thiagoasd** [fiote/treeofsavior-addons#23]
Hi,
First of all, Thank you for your addon! really great.
So, I'd like to know if it's possible to deactivate /farmed xp and /farmed xpjob without the need to use the commands every time I log in. I tried modifying my cwfarmed.lua file in these options but no luck:

```
defaults.show.xp = false;
defaults.show.xpjob = false;
defaults.show.pet = false;
```
Is it possible for deactivating it for good instead of for sessions? 
Thanks

**Comment by fiote** [comment]
Hi @thiagoasd. Everytime you alter a value using a /farmed command, it should store it on the cwfarmed.json... and when the game load, the last settings should be read from there. From what you're telling me, it seems like that save/load flow isn't working properly. I'll take a look.

**Comment by thiagoasd** [comment]
Thanks for the fast response! If you need any help with logs or something like that, please tell me so :)

**Comment by fiote** [comment]
@thiagoasd should be fixed now. Get the newest release :)
