### ISSUE TITLE
depends on Excrulon

### ISSUE THREAD

**Issue by White-Tiger** [fiote/treeofsavior-addons#24]
you should mention that your addons do in fact depend on Excrulon's addon loader...
Without that already installed, your addons won't load at all *(they can't logically)*

You didn't mention this in the install "instructions" and furthermore, you'll claim your addons to be "Excrulon compatible" which is misleading. *(as it didn't said it'll actually require them)*

**Comment by fiote** [comment]
Indeed, you're right!

Just updated my README. Thanks! o/

**Comment by White-Tiger** [comment]
do you know the reason behind why SumAni.ipf was chosen as the "loader"?
Ok, it works without the Unicode "glitch" and might even work once that's fixed.. but wouldn't it be better to create something like:
🔌addonloader.ipl

would be less obscure to the user and doesn't tamper with game files which also makes it update compatible *(as long as the Lua integration and scripts are)*

**Comment by fiote** [comment]
@White-Tiger yeah it would be better... but then again I'm following the norm and will be moving everything to IPF soon, so the loader won't be needed. Guess it'll stay as it is. (and no, I don't know why sumAni was chosen among the others, lol).

**Comment by TehSeph** [comment]
It's the smallest ipf.

**Comment by Excrulon** [comment]
Yep, smallest and easiest to repack. It was originally what I put only the expviewer in and nothing else. Updates don't even matter and won't interfere. None of the ipfs in the data folder ever get updated. Updates are put in the patch folder.
