### ISSUE TITLE
cwset.json missing

### ISSUE THREAD

**Issue by Wolf1030** [fiote/treeofsavior-addons#25]
Getting this error, checked the folder hierarchy and it's not there, checked here as well and also not here. 

http://puu.sh/p5RvC/73aec1751c.jpg

**Comment by fiote** [comment]
Does it stop execution? It doesn't need to be there, and the code should fallback to default values. But i'll check that anyway. Thanks!

**Comment by Navitron** [comment]
It appears when you haven't saved a equipment set yet. Once you make on it goes away.

**Comment by fiote** [comment]
@Navitron yeah because saving a set write downs to that file. And when the addon is initializated, it tries to read the file to load whatever set you saved on previous sessions :)

**Comment by fiote** [comment]
This was solved in the newest release.
