### ISSUE TITLE
[Suggestion] cw Menu

### ISSUE THREAD

**Issue by S-Loxe** [fiote/treeofsavior-addons#26]
E aii Fiote!!! <( ^•^)/

I was wondering if it's possible to add a slash command menu like LK Chat "/lkc" or "/lkchat" (or a button menu like the Exp Calc from Excrulon) so we can use check boxes to turn on/off and change values in there. Not sure if it should record the changes but every time that I close the game I have to change my preferences again like turning XP off. Besides it would be a really great visual way to change the preferences of your addons :3
Sorry if I'm being inconvenient by asking those stuff, and thanks for your hard work! =D

**Comment by fiote** [comment]
About having to change preferences every time: are you sure you have the most recent release? That was fixed on the latest one.

About a UI for config: I'll do that when I move my addons to the IPF format. Will do it soon™ :)
