### ISSUE TITLE
cwset naming issue

### ISSUE THREAD

**Issue by gomuG** [fiote/treeofsavior-addons#27]
using a quotations " " for the name bugs the entire addon loader and makes it unable to fully load(?)

EG /set save "Farming"

**Comment by fiote** [comment]
Ehhhh you shouldn't really use quotes on that. Please open the /addons/cwset/cwset.json file and remove that part from the name of the set. If you're not sure how to change it, simply delete ths cwset.json and restart the game (you'll need to save the set again). 

Keep names simple lol, no more quotes for you :p
