### ISSUE TITLE
[Suggestion] CXScanner

### ISSUE THREAD

**Issue by maxchaoz** [fiote/treeofsavior-addons#30]
Hi friend, I have saw before your CXScanner addon and I think it's a marvelous addon, but I'm not seeing it more on your repo and so on, have you dropped him?
If yes, could you please reevaluate this decision, the idea of seeing the prices is the best.

Thanks for your hard work.

**Comment by fiote** [comment]
@maxchaoz cx* addons are private and were uploaded by mistake. Sorry!

**Comment by ShyPixie** [comment]
@maxchaoz The last version is here [73a6afc](https://github.com/fiote/treeofsavior-addons/blob/73a6afc017dab294b049906418ae54cd753216c4/cxscanner/cxscanner.lua)

We can continue in another repository, since the code is open and is not licensed...

**Comment by Acidhub** [comment]
These cx* addons smells like permban to me.

Let's see what IMC thinks about :+1:
