### ISSUE TITLE
[cwFarmed] options.minAlert.silver not respected.

### ISSUE THREAD

**Issue by TehSeph** [fiote/treeofsavior-addons#4]
There doesn't actually seem to be a minimum silver implementation in the code at all, despite this setting's existence in the .json file. Would love to see this feature, too.

**Comment by fiote** [comment]
Yeah, it's on the settings because it's on my future plans for the addon ^^ Since you're asking about it, I'll try to get it done sooner.

**Comment by fiote** [comment]
Hi @TehSeph! The new release (1.0.2) got this feature added :)
