### ISSUE TITLE
[cwCleric] System spam for non-cleric classes.

### ISSUE THREAD

**Issue by TehSeph** [fiote/treeofsavior-addons#5]
![System Spam](http://i.imgur.com/itM4kVJ.png)
Same thing goes for clerics without the attribute purchased.

**Comment by fiote** [comment]
Sorry @TehSeph! I'll try to upload a fix for that today!

**Comment by TehSeph** [comment]
All good. Just letting you know. :+1:

**Comment by fiote** [comment]
Just pushed a fix and udpated the last release zip with the changes. Thanks!
