### ISSUE TITLE
[v1.0.2] Farmed amount is not shown

### ISSUE THREAD

**Issue by virgilioneto** [fiote/treeofsavior-addons#6]
Hi @fiote, thanks for the great addon.
The silver amount in session isn't working, just the chat system message.

It's possible to see in this video.
https://youtu.be/_5NFgQ8TS_E

**Complementary information**
**Addon version**: 1.0.2
**Excrulon addon version**: 1.7

**Comment by holysnipz** [comment]
already fixed, but not publish yet
you can grab new cwFarmed [here](https://github.com/fiote/treeofsavior-addons/blob/master/cwfarmed/cwfarmed.lua)

**Comment by virgilioneto** [comment]
Updated and tested. Now working fine. Thanks.

**Comment by fiote** [comment]
Yeah, I pushed the fixes but did not updated the release. I promised doing that yesterday but I could not. I'll try to update it today!

**Comment by fiote** [comment]
Fixed on release 1.0.3.
