### ISSUE TITLE
[v1.0.2] Boss box re-roll window missing

### ISSUE THREAD

**Issue by virgilioneto** [fiote/treeofsavior-addons#7]
Hi @fiote.
Yes, sounds strange, but true.
With the old version (v0.1.0) this works properly.

It's possible to see in this video.
https://youtu.be/tFfeIaU_2jg 

**Complementary information**
**Addon version**: 1.0.2
**Excrulon addon version**: 1.7

**Comment by holysnipz** [comment]
already fixed, but not publish yet
you can grab new cwFarmed [here](https://github.com/fiote/treeofsavior-addons/blob/master/cwfarmed/cwfarmed.lua)

**Comment by fiote** [comment]
Fixed on release 1.0.3
